name: Check service compiles
author: jakub.filo
description: Basic check to test if service compiles successfully

runs:
  using: composite

  steps:
  - uses: actions/checkout@v5
  - name: Set up JDK
    uses: actions/setup-java@v5
    with:
      java-version-file: .java-version
      distribution: corretto

  - name: Maven cache
    uses: actions/cache/restore@v4
    id: maven-cache
    with:
      path: ~/.m2
      key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      restore-keys: |
        ${{ runner.os }}-m2-
  - name: Build with Maven
    shell: sh
    run: ./mvnw -B compile
  - name: Save cache if not hit
    if: steps.maven-cache.outputs.cache-hit != 'true'
    uses: actions/cache/save@v4
    with:
      path: ~/.m2
      key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}